// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrhmULieoEeDGFKkk7W_-UxPe_2jwC-dw',
    appId: '1:946257666635:web:f44e6a9d7dde822d77e3ce',
    messagingSenderId: '946257666635',
    projectId: 'teamup-e83fd',
    authDomain: 'teamup-e83fd.firebaseapp.com',
    storageBucket: 'teamup-e83fd.firebasestorage.app',
    measurementId: 'G-J2DP96STT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYh-Ad0FbJFqRbBaiV6X6LW4lgG3idDzs',
    appId: '1:946257666635:android:b057d6a89bfe16a877e3ce',
    messagingSenderId: '946257666635',
    projectId: 'teamup-e83fd',
    storageBucket: 'teamup-e83fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0e9CUfJyVB2neggCC6zjrN1Eq3JC-lvA',
    appId: '1:946257666635:ios:dbb7ae737efb3aca77e3ce',
    messagingSenderId: '946257666635',
    projectId: 'teamup-e83fd',
    storageBucket: 'teamup-e83fd.firebasestorage.app',
    iosBundleId: 'com.example.teamUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0e9CUfJyVB2neggCC6zjrN1Eq3JC-lvA',
    appId: '1:946257666635:ios:dbb7ae737efb3aca77e3ce',
    messagingSenderId: '946257666635',
    projectId: 'teamup-e83fd',
    storageBucket: 'teamup-e83fd.firebasestorage.app',
    iosBundleId: 'com.example.teamUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrhmULieoEeDGFKkk7W_-UxPe_2jwC-dw',
    appId: '1:946257666635:web:64a541e14cf105ea77e3ce',
    messagingSenderId: '946257666635',
    projectId: 'teamup-e83fd',
    authDomain: 'teamup-e83fd.firebaseapp.com',
    storageBucket: 'teamup-e83fd.firebasestorage.app',
    measurementId: 'G-TH0TZY53D7',
  );
}
